marketItemsDatabase = {
  -- Ammunations  
  {
    name = "Bolt",
    category = 13,
    tradeAs = 3446,
    showAs = 3446,
  },
  {
    name = "Arrow",
    category = 13,
    tradeAs = 3447,
    showAs = 3447,
  },
  {
    name = "Poison Arrow",
    category = 13,
    tradeAs = 3448,
    showAs = 3448,
  },
  {
    name = "Burst Arrow",
    category = 13,
    tradeAs = 3449,
    showAs = 3449,
  },
  {
    name = "Power Bolt",
    category = 13,
    tradeAs = 3450,
    showAs = 3450,
  },
  {
    name = "Power Bolt",
    category = 13,
    tradeAs = 3450,
    showAs = 3450,
  },
  {
    name = "Infernal Bolt",
    category = 13,
    tradeAs = 6528,
    showAs = 6528,
  },
  {
    name = "Piercing Bolt",
    category = 13,
    tradeAs = 7363,
    showAs = 7363,
  },
  {
    name = "Sniper Arrow",
    category = 13,
    tradeAs = 7364,
    showAs = 7364,
  },
  {
    name = "Onyx Arrow",
    category = 13,
    tradeAs = 7365,
    showAs = 7365,
  },
  -- Amulets  
  {
    name = "Crystal Necklace",
    category = 6,
    tradeAs = 3008,
    showAs = 3008,
  },
  {
    name = "Bronze Necklace",
    category = 6,
    tradeAs = 3009,
    showAs = 3009,
  },
  {
    name = "Wolf Tooth Chain",
    category = 6,
    tradeAs = 3012,
    showAs = 3012,
  },
  {
    name = "Golden Amulet",
    category = 6,
    tradeAs = 3013,
    showAs = 3013,
  },
  {
    name = "Star Amulet",
    category = 6,
    tradeAs = 3014,
    showAs = 3014,
  },
  {
    name = "Ruby Necklace",
    category = 6,
    tradeAs = 3016,
    showAs = 3016,
  },
  {
    name = "Scarab Amulet",
    category = 6,
    tradeAs = 3018,
    showAs = 3018,
  },
  {
    name = "Demonbone Amulet",
    category = 6,
    tradeAs = 3019,
    showAs = 3019,
  },
  {
    name = "Saphire Amulet",
    category = 6,
    tradeAs = 3021,
    showAs = 3021,
  },
  {
    name = "Ancient Amulet",
    category = 6,
    tradeAs = 3025,
    showAs = 3025,
  },
  {
    name = "Strange Talisman",
    category = 6,
    tradeAs = 3045,
    showAs = 3045,
  },
  {
    name = "Silver Amulet",
    category = 6,
    tradeAs = 3015,
    showAs = 3015,
  },
  {
    name = "Bronze Amulet",
    category = 6,
    tradeAs = 3009,
    showAs = 3009,
  },
  {
    name = "Amulet of Loss",
    category = 6,
    tradeAs = 3057,
    showAs = 3057,
  },
  {
    name = "Broken Amulet",
    category = 6,
    tradeAs = 3080,
    showAs = 3080,
  },
  {
    name = "Stone Skin Amulet",
    category = 6,
    tradeAs = 3081,
    showAs = 3081,
  },
  {
    name = "Elven Amulet",
    category = 6,
    tradeAs = 3082,
    showAs = 3082,
  },
  {
    name = "Garlic Necklace",
    category = 6,
    tradeAs = 3083,
    showAs = 3083,
  },
  {
    name = "Protection Amulet",
    category = 6,
    tradeAs = 3084,
    showAs = 3084,
  },
  {
    name = "Dragon Necklace",
    category = 6,
    tradeAs = 3085,
    showAs = 3085,
  },
  {
    name = "Paw Amulet",
    category = 6,
    tradeAs = 3102,
    showAs = 3102,
  },
  {
    name = "Scarf",
    category = 6,
    tradeAs = 3572,
    showAs = 3572,
  },
  -- Armors
  {
    name = "Ball Gown",
    category = 2,
    tradeAs = 3570,
    showAs = 3570,
  },
  {
    name = "Simple Dress",
    category = 2,
    tradeAs = 3568,
    showAs = 3568,
  },
  {
    name = "White Dress",
    category = 2,
    tradeAs = 3569,
    showAs = 3569,
  },
  {
    name = "Spectral Dress",
    category = 2,
    tradeAs = 4836,
    showAs = 4836,
  },
  {
    name = "Jacket",
    category = 2,
    tradeAs = 3561,
    showAs = 3561,
  },
  {
    name = "Coat",
    category = 2,
    tradeAs = 3562,
    showAs = 3562,
  },
  {
    name = "Green Tunic",
    category = 2,
    tradeAs = 3563,
    showAs = 3563,
  },
  {
    name = "Cape",
    category = 2,
    tradeAs = 3565,
    showAs = 3565,
  },
  {
    name = "Red Robe",
    category = 2,
    tradeAs = 3566,
    showAs = 3566,
  },
  {
    name = "Doublet",
    category = 2,
    tradeAs = 3379,
    showAs = 3379,
  },
  {
    name = "Red Tunic",
    category = 2,
    tradeAs = 3564,
    showAs = 3564,
  },
  {
    name = "Pirate Shirt",
    category = 2,
    tradeAs = 6095,
    showAs = 6095,
  },
  {
    name = "Leather Armor",
    category = 2,
    tradeAs = 3361,
    showAs = 3361,
  },
  {
    name = "Studded Armor",
    category = 2,
    tradeAs = 3378,
    showAs = 3378,
  },
  {
    name = "Chain Armor",
    category = 2,
    tradeAs = 3358,
    showAs = 3358,
  },
  {
    name = "Rangers Cloak",
    category = 2,
    tradeAs = 3571,
    showAs = 3571,
  },
  {
    name = "Native Armor",
    category = 2,
    tradeAs = 3402,
    showAs = 3402,
  },
  {
    name = "Brass Armor",
    category = 2,
    tradeAs = 3359,
    showAs = 3359,
  },
  {
    name = "Scale Armor",
    category = 2,
    tradeAs = 3377,
    showAs = 3377,
  },
  {
    name = "Elven Mail",
    category = 2,
    tradeAs = 3399,
    showAs = 3399,
  },
  {
    name = "Leopard Armor",
    category = 2,
    tradeAs = 3404,
    showAs = 3404,
  },
  {
    name = "Plate Armor",
    category = 2,
    tradeAs = 3357,
    showAs = 3357,
  },
  {
    name = "Dark Armor",
    category = 2,
    tradeAs = 3383,
    showAs = 3383,
  },
  {
    name = "Dwarven Armor",
    category = 2,
    tradeAs = 3397,
    showAs = 3397,
  },
  {
    name = "Mammoth Fur Cape",
    category = 2,
    tradeAs = 7463,
    showAs = 7463,
  },
  {
    name = "Noble Armor",
    category = 2,
    tradeAs = 3380,
    showAs = 3380,
  },
  {
    name = "Blue Robe",
    category = 2,
    tradeAs = 3567,
    showAs = 3567,
  },
  {
    name = "Knight Armor",
    category = 2,
    tradeAs = 3370,
    showAs = 3370,
  },
  {
    name = "Crown Armor",
    category = 2,
    tradeAs = 3381,
    showAs = 3381,
  },
  {
    name = "Amazon Armor",
    category = 2,
    tradeAs = 3394,
    showAs = 3394,
  },
  {
    name = "Golden Armor",
    category = 2,
    tradeAs = 3360,
    showAs = 3360,
  },
  {
    name = "Dragon Scale Mail",
    category = 2,
    tradeAs = 3386,
    showAs = 3386,
  },
  {
    name = "Demon Armor",
    category = 2,
    tradeAs = 3388,
    showAs = 3388,
  },
  {
    name = "Magic Plate Armor",
    category = 2,
    tradeAs = 3366,
    showAs = 3366,
  },
  -- Axe
  {
    name = "Sickle",
    category = 9,
    tradeAs = 3293,
    showAs = 3293,
  },
  {
    name = "Hand Axe",
    category = 9,
    tradeAs = 3268,
    showAs = 3268,
  },
  {
    name = "Axe",
    category = 9,
    tradeAs = 3274,
    showAs = 3274,
  },
  {
    name = "Golden Sickle",
    category = 9,
    tradeAs = 2418,
    showAs = 2418,
  },
  {
    name = "Hatchet",
    category = 9,
    tradeAs = 3276,
    showAs = 3276,
  },
  {
    name = "Daramian Axe",
    category = 9,
    tradeAs = 3329,
    showAs = 3329,
  },
  {
    name = "Orcish Axe",
    category = 9,
    tradeAs = 3316,
    showAs = 3316,
  },
  {
    name = "Battle Axe",
    category = 9,
    tradeAs = 3266,
    showAs = 3266,
  },
  {
    name = "Barbarian Axe",
    category = 9,
    tradeAs = 3317,
    showAs = 3317,
  },
  {
    name = "Ripper Lance",
    category = 9,
    tradeAs = 3346,
    showAs = 3346,
  },
  {
    name = "Dwarven Axe",
    category = 9,
    tradeAs = 3323,
    showAs = 3323,
  },
  {
    name = "Knight Axe",
    category = 9,
    tradeAs = 3318,
    showAs = 3318,
  },
  {
    name = "Obsidian Lance",
    category = 9,
    tradeAs = 3313,
    showAs = 3313,
  },
  {
    name = "Halberd",
    category = 9,
    tradeAs = 3269,
    showAs = 3269,
  },
  {
    name = "Double Axe",
    category = 9,
    tradeAs = 3275,
    showAs = 3275,
  },
  {
    name = "Beastslayer Axe",
    category = 9,
    tradeAs = 3344,
    showAs = 3344,
  },
  {
    name = "Fire Axe",
    category = 9,
    tradeAs = 3320,
    showAs = 3320,
  },
  {
    name = "Naginata",
    category = 9,
    tradeAs = 3314,
    showAs = 3314,
  },
  {
    name = "Daramian Waraxe",
    category = 9,
    tradeAs = 3328,
    showAs = 3328,
  },
  {
    name = "Noble Axe",
    category = 9,
    tradeAs = 7436,
    showAs = 7436,
  },
  {
    name = "Dreaded Cleaver",
    category = 9,
    tradeAs = 7419,
    showAs = 7419,
  },
  {
    name = "Glorious Axe",
    category = 9,
    tradeAs = 7454,
    showAs = 7454,
  },
  {
    name = "Butcher's Axe",
    category = 9,
    tradeAs = 7412,
    showAs = 7412,
  },
  {
    name = "Headchopper",
    category = 9,
    tradeAs = 7380,
    showAs = 7380,
  },
  {
    name = "Ornamented Axe",
    category = 9,
    tradeAs = 7411,
    showAs = 7411,
  },
  {
    name = "Vile Axe",
    category = 9,
    tradeAs = 7388,
    showAs = 7388,
  },
  {
    name = "Titan Axe",
    category = 9,
    tradeAs = 7413,
    showAs = 7413,
  },
  {
    name = "Heroic Axe",
    category = 9,
    tradeAs = 7389,
    showAs = 7389,
  },
  {
    name = "Angelic Axe",
    category = 9,
    tradeAs = 7436,
    showAs = 7436,
  },
  {
    name = "Twin Axe",
    category = 9,
    tradeAs = 7389,
    showAs = 7389,
  },
  {
    name = "Ravenwing",
    category = 9,
    tradeAs = 7433,
    showAs = 7433,
  },
  {
    name = "Guardian Halberd",
    category = 9,
    tradeAs = 3315,
    showAs = 3315,
  },
  {
    name = "Reaper's Axe",
    category = 9,
    tradeAs = 7420,
    showAs = 7420,
  },
  {
    name = "Dragon Lance",
    category = 9,
    tradeAs = 3302,
    showAs = 3302,
  },
  {
    name = "Royal Axe",
    category = 9,
    tradeAs = 7434,
    showAs = 7434,
  },
  {
    name = "War Axe",
    category = 9,
    tradeAs = 3342,
    showAs = 3342,
  },
  {
    name = "Mythril Axe",
    category = 9,
    tradeAs = 7455,
    showAs = 7455,
  },
  {
    name = "Ravager's Axe",
    category = 9,
    tradeAs = 3331,
    showAs = 3331,
  },
  {
    name = "Impaler",
    category = 9,
    tradeAs = 7435,
    showAs = 7435,
  },
  {
    name = "Stonecutter's Axe",
    category = 9,
    tradeAs = 3319,
    showAs = 3319,
  },
  {
    name = "Ruthless Axe",
    category = 9,
    tradeAs = 6553,
    showAs = 6553,
  },
  {
    name = "Executioner",
    category = 9,
    tradeAs = 7453,
    showAs = 7453,
  },
  {
    name = "Great Axe",
    category = 9,
    tradeAs = 3303,
    showAs = 3303,
  },
  -- Boots
  {
    name = "Boots Of Haste",
    category = 4,
    tradeAs = 3079,
    showAs = 3079,
  },
  {
    name = "Boots of Waterwalking",
    category = 4,
    tradeAs = 3246,
    showAs = 3246,
  },
  {
    name = "Pair of Soft Boots",
    category = 4,
    tradeAs = 6529,
    showAs = 6529,
  },
  {
    name = "Sandals",
    category = 4,
    tradeAs = 3551,
    showAs = 3551,
  },
  {
    name = "Bunnyslippers",
    category = 4,
    tradeAs = 3553,
    showAs = 3553,
  },
  {
    name = "Leather Boots",
    category = 4,
    tradeAs = 3552,
    showAs = 3552,
  },
  {
    name = "Crocodile Boots",
    category = 4,
    tradeAs = 3556,
    showAs = 3556,
  },
  {
    name = "Patched Boots",
    category = 4,
    tradeAs = 3550,
    showAs = 3550,
  },
  {
    name = "Pirate Boots",
    category = 4,
    tradeAs = 5461,
    showAs = 5461,
  },
  {
    name = "Fur Boots",
    category = 4,
    tradeAs = 7457,
    showAs = 7457,
  },
  {
    name = "Steel Boots",
    category = 4,
    tradeAs = 3554,
    showAs = 3554,
  },
  {
    name = "Golden Boots",
    category = 4,
    tradeAs = 3555,
    showAs = 3555,
  },
  -- Clubs
  {
    name = "Crowbar",
    category = 10,
    tradeAs = 3304,
    showAs = 3304,
  },
  {
    name = "Club",
    category = 10,
    tradeAs = 3270,
    showAs = 3270,
  },
  {
    name = "Studded Club",
    category = 10,
    tradeAs = 3336,
    showAs = 3336,
  },
  {
    name = "Staff",
    category = 10,
    tradeAs = 3289,
    showAs = 3289,
  },
  {
    name = "Enchanted Staff",
    category = 10,
    tradeAs = 3321,
    showAs = 3321,
  },
  {
    name = "Bone Club",
    category = 10,
    tradeAs = 3337,
    showAs = 3337,
  },
  {
    name = "Light Mace",
    category = 10,
    tradeAs = 3325,
    showAs = 3325,
  },
  {
    name = "Mace",
    category = 10,
    tradeAs = 3286,
    showAs = 3286,
  },
  {
    name = "Iron Hammer",
    category = 10,
    tradeAs = 3310,
    showAs = 3310,
  },
  {
    name = "Daramian Waraxe",
    category = 9,
    tradeAs = 3328,
    showAs = 3328,
  },
  {
    name = "Giant Smithhammer",
    category = 10,
    tradeAs = 3208,
    showAs = 3208,
  },
  {
    name = "Battle Hammer",
    category = 10,
    tradeAs = 3305,
    showAs = 3305,
  },
  {
    name = "Morning Star",
    category = 10,
    tradeAs = 3282,
    showAs = 3282,
  },
  {
    name = "Banana Staff",
    category = 10,
    tradeAs = 3348,
    showAs = 3348,
  },
  {
    name = "Clerical Mace",
    category = 10,
    tradeAs = 3311,
    showAs = 3311,
  },
  {
    name = "Mammoth Whopper",
    category = 10,
    tradeAs = 7381,
    showAs = 7381,
  },
  {
    name = "Taurus Mace",
    category = 10,
    tradeAs = 7425,
    showAs = 7425,
  },
  {
    name = "Furry Club",
    category = 10,
    tradeAs = 7432,
    showAs = 7432,
  },
  {
    name = "Dragon Hammer",
    category = 10,
    tradeAs = 3322,
    showAs = 3322,
  },
  {
    name = "Diamond Sceptre",
    category = 10,
    tradeAs = 7387,
    showAs = 7387,
  },
  {
    name = "Brutetamer's Staff",
    category = 10,
    tradeAs = 7379,
    showAs = 7379,
  },
  {
    name = "Dragonbone Staff",
    category = 10,
    tradeAs = 7430,
    showAs = 7430,
  },
  {
    name = "Skull Staff",
    category = 10,
    tradeAs = 3324,
    showAs = 3324,
  },
  {
    name = "Sapphire Hammer",
    category = 10,
    tradeAs = 7437,
    showAs = 7437,
  },
  {
    name = "Crystal Mace",
    category = 10,
    tradeAs = 3333,
    showAs = 3333,
  },
  {
    name = "Shadow Sceptre",
    category = 10,
    tradeAs = 7451,
    showAs = 7451,
  },
  {
    name = "Lunar Staff",
    category = 10,
    tradeAs = 7424,
    showAs = 7424,
  },
  {
    name = "Lich Staff",
    category = 10,
    tradeAs = 3343,
    showAs = 3343,
  },
  {
    name = "Silver Mace",
    category = 10,
    tradeAs = 3312,
    showAs = 3312,
  },
  {
    name = "Spiked Squelcher",
    category = 10,
    tradeAs = 7452,
    showAs = 7452,
  },
  {
    name = "Orcish Maul",
    category = 10,
    tradeAs = 7392,
    showAs = 7392,
  },
  {
    name = "Northern Star",
    category = 10,
    tradeAs = 7409,
    showAs = 7409,
  },
  {
    name = "Queen's Sceptre",
    category = 10,
    tradeAs = 7410,
    showAs = 7410,
  },
  {
    name = "Amber Staff",
    category = 10,
    tradeAs = 7426,
    showAs = 7426,
  },
  {
    name = "Cranial Basher",
    category = 10,
    tradeAs = 7415,
    showAs = 7415,
  },
  {
    name = "Chaos Mace",
    category = 10,
    tradeAs = 7427,
    showAs = 7427,
  },
  {
    name = "War Hammer",
    category = 10,
    tradeAs = 3279,
    showAs = 3279,
  },
  {
    name = "Onyx Flail",
    category = 10,
    tradeAs = 7421,
    showAs = 7421,
  },
  {
    name = "Jade Hammer",
    category = 10,
    tradeAs = 7422,
    showAs = 7422,
  },
  {
    name = "Bonebreaker",
    category = 10,
    tradeAs = 7428,
    showAs = 7428,
  },
  {
    name = "Abyss Hammer",
    category = 10,
    tradeAs = 7414,
    showAs = 7414,
  },
  {
    name = "Blessed Sceptre",
    category = 10,
    tradeAs = 7429,
    showAs = 7429,
  },
  {
    name = "Hammer of Wrath",
    category = 10,
    tradeAs = 3332,
    showAs = 3332,
  },
  {
    name = "Demonbone",
    category = 10,
    tradeAs = 7431,
    showAs = 7431,
  },
  {
    name = "Thunder Hammer",
    category = 10,
    tradeAs = 3309,
    showAs = 3309,
  },
  {
    name = "Heavy Mace",
    category = 10,
    tradeAs = 3340,
    showAs = 3340,
  },
  {
    name = "Arcane Staff",
    category = 10,
    tradeAs = 3341,
    showAs = 3341,
  },
  {
    name = "Skullcrusher",
    category = 10,
    tradeAs = 7423,
    showAs = 7423,
  },
  {
    name = "Hammer of Prophecy",
    category = 10,
    tradeAs = 7450,
    showAs = 7450,
  },
  -- Distance
  {
    name = "Snowball",
    category = 12,
    tradeAs = 2992,
    showAs = 2992,
  },
  {
    name = "Small Stone",
    category = 12,
    tradeAs = 1781,
    showAs = 1781,
  },
  {
    name = "Spear",
    category = 12,
    tradeAs = 3277,
    showAs = 3277,
  },
  {
    name = "Throwing Knife",
    category = 12,
    tradeAs = 3298,
    showAs = 3298,
  },
  {
    name = "Viper Star",
    category = 12,
    tradeAs = 7366,
    showAs = 7366,
  },
  {
    name = "Throwing Star",
    category = 12,
    tradeAs = 3287,
    showAs = 3287,
  },
  {
    name = "Hunting Spear",
    category = 12,
    tradeAs = 3347,
    showAs = 3347,
  },
  {
    name = "Royal Spear",
    category = 12,
    tradeAs = 7378,
    showAs = 7378,
  },
  {
    name = "Enchanted Spear",
    category = 12,
    tradeAs = 7367,
    showAs = 7367,
  },
  {
    name = "Assassin Star",
    category = 12,
    tradeAs = 7368,
    showAs = 7368,
  },
  {
    name = "Crossbow",
    category = 12,
    tradeAs = 3349,
    showAs = 3349,
  },
  {
    name = "Arbalest",
    category = 12,
    tradeAs = 5803,
    showAs = 5803,
  },
  {
    name = "Bow",
    category = 12,
    tradeAs = 3350,
    showAs = 3350,
  },
  {
    name = "Elvish Bow",
    category = 12,
    tradeAs = 7438,
    showAs = 7438,
  },
  -- Helmets
  {
    name = "Ancient Tiara",
    category = 1,
    tradeAs = 3022,
    showAs = 3022,
  },
  {
    name = "Crown",
    category = 1,
    tradeAs = 3011,
    showAs = 3011,
  },
  {
    name = "Pair of Earmuffs",
    category = 1,
    tradeAs = 7459,
    showAs = 7459,
  },
  {
    name = "Bandana",
    category = 1,
    tradeAs = 5917,
    showAs = 5917,
  },
  {
    name = "Santa Hat",
    category = 1,
    tradeAs = 6531,
    showAs = 6531,
  },
  {
    name = "Leather Helmet",
    category = 1,
    tradeAs = 3355,
    showAs = 3355,
  },
  {
    name = "Tribal Mask",
    category = 1,
    tradeAs = 3403,
    showAs = 3403,
  },
  {
    name = "Chain Helme",
    category = 1,
    tradeAs = 3352,
    showAs = 3352,
  },
  {
    name = "Charmer's Tiara",
    category = 1,
    tradeAs = 3407,
    showAs = 3407,
  },
  {
    name = "Feather Headdress",
    category = 1,
    tradeAs = 3406,
    showAs = 3406,
  },
  {
    name = "Helmet of the Deep",
    category = 1,
    tradeAs = 5460,
    showAs = 5460,
  },
  {
    name = "Studded Helmet",
    category = 1,
    tradeAs = 3376,
    showAs = 3376,
  },
  {
    name = "Brass Helmet",
    category = 1,
    tradeAs = 3354,
    showAs = 3354,
  },
  {
    name = "Viking Helmet",
    category = 1,
    tradeAs = 3367,
    showAs = 3367,
  },
  {
    name = "Pirate Hat",
    category = 1,
    tradeAs = 6096,
    showAs = 6096,
  },
  {
    name = "Legion Helmet",
    category = 1,
    tradeAs = 3374,
    showAs = 3374,
  },
  {
    name = "Soldier Helmet",
    category = 1,
    tradeAs = 3375,
    showAs = 3375,
  },
  {
    name = "Iron Helmet",
    category = 1,
    tradeAs = 3353,
    showAs = 3353,
  },
  {
    name = "Steel Helmet",
    category = 1,
    tradeAs = 3351,
    showAs = 3351,
  },
  {
    name = "Horseman Helmet",
    category = 1,
    tradeAs = 3405,
    showAs = 3405,
  },
  {
    name = "Dark Helmet",
    category = 1,
    tradeAs = 3384,
    showAs = 3384,
  },
  {
    name = "Strange Helmet",
    category = 1,
    tradeAs = 3373,
    showAs = 3373,
  },
  {
    name = "Amazon Helmet",
    category = 1,
    tradeAs = 3393,
    showAs = 3393,
  },
  {
    name = "Beholder Helmet",
    category = 1,
    tradeAs = 3408,
    showAs = 3408,
  },
  {
    name = "Dwarven Helmet",
    category = 1,
    tradeAs = 3396,
    showAs = 3396,
  },
  {
    name = "Mystic Turban",
    category = 1,
    tradeAs = 3574,
    showAs = 3574,
  },
  {
    name = "Fur Cap",
    category = 1,
    tradeAs = 7458,
    showAs = 7458,
  },
  {
    name = "Hat Of The Mad",
    category = 1,
    tradeAs = 3210,
    showAs = 3210,
  },
  {
    name = "Magician's Hat",
    category = 1,
    tradeAs = 3573,
    showAs = 3573,
  },
  {
    name = "Post Officers Hat",
    category = 1,
    tradeAs = 3576,
    showAs = 3576,
  },
  {
    name = "Krimhorn Helmet",
    category = 1,
    tradeAs = 7461,
    showAs = 7461,
  },
  {
    name = "Ragnir Helmet",
    category = 1,
    tradeAs = 7462,
    showAs = 7462,
  },
  {
    name = "Crown Helmet",
    category = 1,
    tradeAs = 3385,
    showAs = 3385,
  },
  {
    name = "Devil Helmet",
    category = 1,
    tradeAs = 3356,
    showAs = 3356,
  },
  {
    name = "Warrior Helmet",
    category = 1,
    tradeAs = 3369,
    showAs = 3369,
  },
  {
    name = "Crusader Helmet",
    category = 1,
    tradeAs = 3391,
    showAs = 3391,
  },
  {
    name = "Helmet of the Ancients",
    category = 1,
    tradeAs = 3229,
    showAs = 3229,
  },
  {
    name = "Ceremonial Mask",
    category = 1,
    tradeAs = 3395,
    showAs = 3395,
  },
  {
    name = "Dragon Scale Helmet",
    category = 1,
    tradeAs = 3400,
    showAs = 3400,
  },
  {
    name = "Royal Helmet",
    category = 1,
    tradeAs = 3392,
    showAs = 3392,
  },
  {
    name = "Skull Helmet",
    category = 1,
    tradeAs = 5741,
    showAs = 5741,
  },
  {
    name = "Demon Helmet",
    category = 1,
    tradeAs = 3387,
    showAs = 3387,
  },
  {
    name = "Winged Helmet",
    category = 1,
    tradeAs = 3368,
    showAs = 3368,
  },
  {
    name = "Horned Helmet",
    category = 1,
    tradeAs = 3390,
    showAs = 3390,
  },
  {
    name = "Full helmet of the Ancients",
    category = 1,
    tradeAs = 3230,
    showAs = 3230,
  },
  {
    name = "Golden Helmet",
    category = 1,
    tradeAs = 3365,
    showAs = 3365,
  },
  -- Legs
  {
    name = "Bast Skirt",
    category = 3,
    tradeAs = 3560,
    showAs = 3560,
  },
  {
    name = "Mammoth Fur Shorts",
    category = 3,
    tradeAs = 7464,
    showAs = 7464,
  },
  {
    name = "Leather Legs",
    category = 3,
    tradeAs = 3559,
    showAs = 3559,
  },
  {
    name = "Pirate Knee Breeches",
    category = 3,
    tradeAs = 5918,
    showAs = 5918,
  },
  {
    name = "Studded Legs",
    category = 3,
    tradeAs = 3362,
    showAs = 3362,
  },
  {
    name = "Chain Legs",
    category = 3,
    tradeAs = 3558,
    showAs = 3558,
  },
  {
    name = "Elven Legs",
    category = 3,
    tradeAs = 3401,
    showAs = 3401,
  },
  {
    name = "Brass Legs",
    category = 3,
    tradeAs = 3372,
    showAs = 3372,
  },
  {
    name = "Dwarven Legs",
    category = 3,
    tradeAs = 3398,
    showAs = 3398,
  },
  {
    name = "Plate Legs",
    category = 3,
    tradeAs = 3557,
    showAs = 3557,
  },
  {
    name = "Knight Legs",
    category = 3,
    tradeAs = 3371,
    showAs = 3371,
  },
  {
    name = "Crown Legs",
    category = 3,
    tradeAs = 3382,
    showAs = 3382,
  },
  {
    name = "Golden Legs",
    category = 3,
    tradeAs = 3364,
    showAs = 3364,
  },
  {
    name = "Demon Legs",
    category = 3,
    tradeAs = 3389,
    showAs = 3389,
  },
  {
    name = "Dragon Scale Legs",
    category = 3,
    tradeAs = 3363,
    showAs = 3363,
  },
  -- Shields
  {
    name = "Wooden Shield",
    category = 5,
    tradeAs = 3412,
    showAs = 3412,
  },
  {
    name = "Studded Shield",
    category = 5,
    tradeAs = 3426,
    showAs = 3426,
  },
  {
    name = "Brass Shield",
    category = 5,
    tradeAs = 3411,
    showAs = 3411,
  },
  {
    name = "Plate Shield",
    category = 5,
    tradeAs = 3410,
    showAs = 3410,
  },
  {
    name = "Black Shield",
    category = 5,
    tradeAs = 3429,
    showAs = 3429,
  },
  {
    name = "Copper Shield",
    category = 5,
    tradeAs = 3430,
    showAs = 3430,
  },
  {
    name = "Bone Shield",
    category = 5,
    tradeAs = 3441,
    showAs = 3441,
  },
  {
    name = "Steel Shield",
    category = 5,
    tradeAs = 3409,
    showAs = 3409,
  },
  {
    name = "Ornamented Shield",
    category = 5,
    tradeAs = 3424,
    showAs = 3424,
  },
  {
    name = "Viking Shield",
    category = 5,
    tradeAs = 3431,
    showAs = 3431,
  },
  {
    name = "Sentinel Shield",
    category = 5,
    tradeAs = 3444,
    showAs = 3444,
  },
  {
    name = "Battle Shield",
    category = 5,
    tradeAs = 3413,
    showAs = 3413,
  },
  {
    name = "Dark Shield",
    category = 5,
    tradeAs = 3421,
    showAs = 3421,
  },
  {
    name = "Scarab Shield",
    category = 5,
    tradeAs = 3440,
    showAs = 3440,
  },
  {
    name = "Dwarven Shield",
    category = 5,
    tradeAs = 3425,
    showAs = 3425,
  },
  {
    name = "Salamander Shield",
    category = 5,
    tradeAs = 3445,
    showAs = 3445,
  },
  {
    name = "Tortoise Shield",
    category = 5,
    tradeAs = 6131,
    showAs = 6131,
  },
  {
    name = "Rose Shield",
    category = 5,
    tradeAs = 3427,
    showAs = 3427,
  },
  {
    name = "Ancient Shield",
    category = 5,
    tradeAs = 3432,
    showAs = 3432,
  },
  {
    name = "Tusk Shield",
    category = 5,
    tradeAs = 3443,
    showAs = 3443,
  },
  {
    name = "Beholder Shield",
    category = 5,
    tradeAs = 3418,
    showAs = 3418,
  },
  {
    name = "Castle Shield",
    category = 5,
    tradeAs = 3435,
    showAs = 3435,
  },
  {
    name = "Norse Shield",
    category = 5,
    tradeAs = 7460,
    showAs = 7460,
  },
  {
    name = "Griffin Shield",
    category = 5,
    tradeAs = 3433,
    showAs = 3433,
  },
  {
    name = "Guardian Shield",
    category = 5,
    tradeAs = 3415,
    showAs = 3415,
  },
  {
    name = "Dragon Shield",
    category = 5,
    tradeAs = 3416,
    showAs = 3416,
  },
  {
    name = "Tempest Shield",
    category = 5,
    tradeAs = 3442,
    showAs = 3442,
  },
  {
    name = "Crown Shield",
    category = 5,
    tradeAs = 3419,
    showAs = 3419,
  },
  {
    name = "Tower Shield",
    category = 5,
    tradeAs = 3428,
    showAs = 3428,
  },
  {
    name = "Amazon Shield",
    category = 5,
    tradeAs = 3437,
    showAs = 3437,
  },
  {
    name = "Eagle Shield",
    category = 5,
    tradeAs = 3438,
    showAs = 3438,
  },
  {
    name = "Shield of Honour",
    category = 5,
    tradeAs = 3417,
    showAs = 3417,
  },
  {
    name = "Medusa Shield",
    category = 5,
    tradeAs = 3436,
    showAs = 3436,
  },
  {
    name = "Vampire Shield",
    category = 5,
    tradeAs = 3434,
    showAs = 3434,
  },
  {
    name = "Phoenix Shield",
    category = 5,
    tradeAs = 3439,
    showAs = 3439,
  },
  {
    name = "Demon Shield",
    category = 5,
    tradeAs = 3420,
    showAs = 3420,
  },
  {
    name = "Mastermind Shield",
    category = 5,
    tradeAs = 3414,
    showAs = 3414,
  },
  {
    name = "Nightmare Shield",
    category = 5,
    tradeAs = 6390,
    showAs = 6390,
  },
  {
    name = "Necromancer Shield",
    category = 5,
    tradeAs = 6432,
    showAs = 6432,
  },
  {
    name = "Great Shield",
    category = 5,
    tradeAs = 3422,
    showAs = 3422,
  },
  {
    name = "Blessed Shield",
    category = 5,
    tradeAs = 3423,
    showAs = 3423,
  },
  -- Swords
  {
    name = "Knife",
    category = 11,
    tradeAs = 3291,
    showAs = 3291,
  },
  {
    name = "Dagger",
    category = 11,
    tradeAs = 3267,
    showAs = 3267,
  },
  {
    name = "Combat Knife",
    category = 11,
    tradeAs = 3292,
    showAs = 3292,
  },
  {
    name = "Silver Dagger",
    category = 11,
    tradeAs = 3290,
    showAs = 3290,
  },
  {
    name = "Rapier",
    category = 11,
    tradeAs = 3272,
    showAs = 3272,
  },
  {
    name = "Short Sword",
    category = 11,
    tradeAs = 3294,
    showAs = 3294,
  },
  {
    name = "Sabre",
    category = 11,
    tradeAs = 3273,
    showAs = 3273,
  },
  {
    name = "Bone Sword",
    category = 11,
    tradeAs = 3338,
    showAs = 3338,
  },
  {
    name = "Sword",
    category = 11,
    tradeAs = 3264,
    showAs = 3264,
  },
  {
    name = "Carlin Sword",
    category = 11,
    tradeAs = 3283,
    showAs = 3283,
  },
  {
    name = "Katana",
    category = 11,
    tradeAs = 3300,
    showAs = 3300,
  },
  {
    name = "Longsword",
    category = 11,
    tradeAs = 3285,
    showAs = 3285,
  },
  {
    name = "Poison Dagger",
    category = 11,
    tradeAs = 3299,
    showAs = 3299,
  },
  {
    name = "Scimitar",
    category = 11,
    tradeAs = 3307,
    showAs = 3307,
  },
  {
    name = "Templar Scytheblade",
    category = 11,
    tradeAs = 3345,
    showAs = 3345,
  },
  {
    name = "Spike Sword",
    category = 11,
    tradeAs = 3271,
    showAs = 3271,
  },
  {
    name = "Serpent Sword",
    category = 11,
    tradeAs = 3297,
    showAs = 3297,
  },
  {
    name = "Broadsword",
    category = 11,
    tradeAs = 3301,
    showAs = 3301,
  },
  {
    name = "Crimson Sword",
    category = 11,
    tradeAs = 7385,
    showAs = 7385,
  },
  {
    name = "Two Handed Sword",
    category = 11,
    tradeAs = 3265,
    showAs = 3265,
  },
  {
    name = "Wyvern Fang",
    category = 11,
    tradeAs = 7408,
    showAs = 7408,
  },
  {
    name = "Fire Sword",
    category = 11,
    tradeAs = 3280,
    showAs = 3280,
  },
  {
    name = "Crystal Sword",
    category = 11,
    tradeAs = 7449,
    showAs = 7449,
  },
  {
    name = "Bright Sword",
    category = 11,
    tradeAs = 3295,
    showAs = 3295,
  },
  {
    name = "Epee",
    category = 11,
    tradeAs = 3326,
    showAs = 3326,
  },
  {
    name = "Djinn Blade",
    category = 11,
    tradeAs = 3339,
    showAs = 3339,
  },
  {
    name = "Assassin Dagger",
    category = 11,
    tradeAs = 7404,
    showAs = 7404,
  },
  {
    name = "Haunted Blade",
    category = 11,
    tradeAs = 7407,
    showAs = 7407,
  },
  {
    name = "Pharaoh Sword",
    category = 11,
    tradeAs = 3334,
    showAs = 3334,
  },
  {
    name = "Relic Sword",
    category = 11,
    tradeAs = 7383,
    showAs = 7383,
  },
  {
    name = "Blacksteel Sword",
    category = 11,
    tradeAs = 7406,
    showAs = 7406,
  },
  {
    name = "Mercenary Sword",
    category = 11,
    tradeAs = 7386,
    showAs = 7386,
  },
  {
    name = "Bloody Edge",
    category = 11,
    tradeAs = 7416,
    showAs = 7416,
  },
  {
    name = "Mystic Blade",
    category = 11,
    tradeAs = 7384,
    showAs = 7384,
  },
  {
    name = "Dragon Slayer",
    category = 11,
    tradeAs = 7402,
    showAs = 7402,
  },
  {
    name = "Thaian Sword",
    category = 11,
    tradeAs = 7391,
    showAs = 7391,
  },
  {
    name = "Runed Sword",
    category = 11,
    tradeAs = 7417,
    showAs = 7417,
  },
  {
    name = "Giant Sword",
    category = 11,
    tradeAs = 3281,
    showAs = 3281,
  },
  {
    name = "Nightmare Blade",
    category = 11,
    tradeAs = 7418,
    showAs = 7418,
  },
  {
    name = "Demonrage Sword",
    category = 11,
    tradeAs = 7382,
    showAs = 7382,
  },
  {
    name = "Justice Seeker",
    category = 11,
    tradeAs = 7390,
    showAs = 7390,
  },
  {
    name = "Magic Sword",
    category = 11,
    tradeAs = 3288,
    showAs = 3288,
  },
  {
    name = "Berserker",
    category = 11,
    tradeAs = 7403,
    showAs = 7403,
  },
  {
    name = "Havoc Blade",
    category = 11,
    tradeAs = 7405,
    showAs = 7405,
  },
  {
    name = "Avenger",
    category = 11,
    tradeAs = 6527,
    showAs = 6527,
  },
  {
    name = "Warlord Sword",
    category = 11,
    tradeAs = 3296,
    showAs = 3296,
  },
  {
    name = "Magic Longsword",
    category = 11,
    tradeAs = 3278,
    showAs = 3278,
  },
  {
    name = "Ice Rapier",
    category = 11,
    tradeAs = 3284,
    showAs = 3284,
  },



  
  -- Magician Staffs
  {
    name = "Wand of Vortex",
    category = 8,
    tradeAs = 3074,
    showAs = 3074,
  },
  {
    name = "Wand of Dragonbreath",
    category = 8,
    tradeAs = 3075,
    showAs = 3075,
  },
  {
    name = "Wand of Plague",
    category = 8,
    tradeAs = 3072,
    showAs = 3072,
  },
  {
    name = "Wand of Cosmic Energy",
    category = 8,
    tradeAs = 3073,
    showAs = 3073,
  },
  {
    name = "Wand of Inferno",
    category = 8,
    tradeAs = 3071,
    showAs = 3071,
  },
  {
    name = "Snakebite Rod",
    category = 8,
    tradeAs = 3066,
    showAs = 3066,
  },
  {
    name = "	Moonlight Rod",
    category = 8,
    tradeAs = 3070,
    showAs = 3070,
  },
  {
    name = "Volcanic Rod",
    category = 8,
    tradeAs = 3069,
    showAs = 3069,
  },
  {
    name = "Quagmire Rod",
    category = 8,
    tradeAs = 3065,
    showAs = 3065,
  },
  {
    name = "Tempest Rod",
    category = 8,
    tradeAs = 3067,
    showAs = 3067,
  },
  {
    name = "Crystal Wand",
    category = 8,
    tradeAs = 3068,
    showAs = 3068,
  },
}
